# =============================================================================
# Replication Script
# =============================================================================
#
# Paper:      Economic Development and Processed Food Demand in China: Evidence from the China Health and Nutrition Survey
# Run ID:     hler_wp_024
# Model:      FE_within (IV using province × wave mean income as instrument for individual income; individual FE for within-person processed food demand)
# Generated:  2026-03-17 (UTC)
#
# NOTE: Adjust the data path(s) in the 'Data Loading' section before running.
# All regression specifications replicate those executed by the HLER pipeline.
# Robust standard errors follow the same choice as the Python analysis
# (HC3 for OLS; HC1 for FE; cluster-robust for DiD / event-study).
# =============================================================================


# ======================================================================
# ---------------------------------------------------------------------------
# Package Loading
# ---------------------------------------------------------------------------
# Install missing packages:  install.packages(readLines('packages.txt'))

library(fixest)
library(ggplot2)
library(jsonlite)
library(lmtest)
library(modelsummary)
library(sandwich)
library(tidyverse)

# ======================================================================
# ---------------------------------------------------------------------------
# Load Canonical Model Specification
# ---------------------------------------------------------------------------
# model_spec.json is the single source of truth generated by the HLER pipeline.
# It captures the exact variables, fixed effects, and SE choices used in Python.
spec <- fromJSON("model_spec.json")

# ======================================================================
# ---------------------------------------------------------------------------
# Data Loading
# ---------------------------------------------------------------------------
# Data path is read from model_spec.json at runtime:
data <- read_csv(spec$data_source)

# ======================================================================
# ---------------------------------------------------------------------------
# Variable Construction
# ---------------------------------------------------------------------------

# ======================================================================
# ---------------------------------------------------------------------------
# Main Regression
# ---------------------------------------------------------------------------
# Build fixed-effects formula from model_spec.json:
indep_vars <- c(spec$independent_variables, spec$controls)
rhs        <- paste(indep_vars, collapse = " + ")
# feols uses ^ to form a compound entity FE (e.g. hhid^line);
# paste with ^ when multiple FE columns, otherwise use single name:
fe_cols <- spec$fixed_effects
fe_part <- if (length(fe_cols) > 1) paste(fe_cols, collapse = "^") else fe_cols[1]
formula_fe <- as.formula(paste(spec$dependent_variable, "~", rhs, "|", fe_part))

# Fixed-effects estimator with robust SEs (type from spec):
model_fe <- feols(formula_fe, data = data, vcov = spec$se_type)
summary(model_fe)

# ======================================================================
# ---------------------------------------------------------------------------
# Heterogeneity Analysis
# ---------------------------------------------------------------------------
# --- by urban/rural status ---
# Cross-sectional OLS on t2 == 1 subgroup:
model_het_1 <- lm(fastfood_vol ~ indinc_cpi + a11 + wave + t1 + t2,
                     data = data %>% filter(t2 == 1))
print(coeftest(model_het_1, vcov = vcovHC(model_het_1, "HC3")))

# Cross-sectional OLS on t2 == 2 subgroup:
model_het_2 <- lm(fastfood_vol ~ indinc_cpi + a11 + wave + t1 + t2,
                     data = data %>% filter(t2 == 2))
print(coeftest(model_het_2, vcov = vcovHC(model_het_2, "HC3")))

# --- by income level (median split) ---
data <- data %>%
  mutate(indinc_cpi_q = ntile(indinc_cpi, 2))
for (g in 1:2) {
  sub  <- data %>% filter(indinc_cpi_q == g)
  m    <- lm(fastfood_vol ~ indinc_cpi + a11 + wave + t1 + t2, data = sub)
  cat("\n--- by income level (median split), group", g, "---\n")
  print(coeftest(m, vcov = vcovHC(m, "HC3")))
}


# ======================================================================
# ---------------------------------------------------------------------------
# Temporal Robustness Check
# ---------------------------------------------------------------------------
# Split at year 2000 (pre / post)
data_pre  <- data %>% filter(wave <  2000)
data_post <- data %>% filter(wave >= 2000)

model_pre  <- lm(fastfood_vol ~ indinc_cpi + a11 + wave + t1 + t2, data = data_pre)
model_post <- lm(fastfood_vol ~ indinc_cpi + a11 + wave + t1 + t2, data = data_post)

cat("\n--- Pre-2000 ---\n")
print(coeftest(model_pre,  vcov = vcovHC(model_pre,  "HC3")))
cat("\n--- Post-2000 ---\n")
print(coeftest(model_post, vcov = vcovHC(model_post, "HC3")))

# ======================================================================
# ---------------------------------------------------------------------------
# Table Export
# ---------------------------------------------------------------------------
dir.create("tables", showWarnings = FALSE)

modelsummary(list("(1)" = model_fe),
            output = "tables/hler_wp_024_results.tex",
            title  = "Main Regression Results")

modelsummary(list("(1)" = model_fe),
            output = "tables/hler_wp_024_results.csv")

# ======================================================================
# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------
dir.create("figures", showWarnings = FALSE)

# Histogram of outcome variable
p_hist <- ggplot(data, aes(x = fastfood_vol)) +
  geom_histogram(bins = 30, fill = "steelblue", colour = "white") +
  labs(title = "Distribution of fastfood_vol", x = "fastfood_vol", y = "Count") +
  theme_minimal()
ggsave("figures/figure_01_hist_fastfood_vol.png", p_hist, width = 7, height = 5)

# Scatter: main predictor vs outcome
p_scatter <- ggplot(data, aes(x = indinc_cpi, y = fastfood_vol)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", colour = "firebrick") +
  labs(title = "indinc_cpi vs fastfood_vol", x = "indinc_cpi", y = "fastfood_vol") +
  theme_minimal()
ggsave("figures/figure_02_scatter_indinc_cpi_fastfood_vol.png", p_scatter, width = 7, height = 5)

# ======================================================================
# ---------------------------------------------------------------------------
# Replication Consistency Check
# ---------------------------------------------------------------------------
# Compares Python (statsmodels) point estimates against R (model_fe).
# Tolerance: abs(diff) < 1e-6.  Logs a warning for any mismatch found.
if (file.exists("python_coefficients.json")) {
  py_coefs <- fromJSON("python_coefficients.json")
  r_coefs  <- coef(model_fe)
  cat("\n=== Replication Consistency Check ===\n")
  all_ok <- TRUE
  for (nm in names(py_coefs)) {
    if (!is.null(r_coefs[nm]) && !is.na(r_coefs[[nm]])) {
      diff <- abs(r_coefs[[nm]] - py_coefs[[nm]])
      if (diff > 1e-6) {
        warning(sprintf(
          "Replication mismatch: %s | Python=%.8f | R=%.8f | diff=%.2e",
          nm, py_coefs[[nm]], r_coefs[[nm]], diff
        ))
        all_ok <- FALSE
      }
    }
  }
  if (all_ok) cat("All coefficients match within tolerance (1e-6).\n")
} else {
  message("python_coefficients.json not found — skipping consistency check.")
}