# =============================================================================
# Replication Script
# =============================================================================
#
# Paper:      Early-Life Status Endowments and Long-Run Survival across the Life Course: Evidence from the CMGPD-Liaoning, 1749-1909
# Run ID:     hler_wp_021
# Model:      FE_within (Person-level panel OLS with individual fixed effects; regress survival indicator (1 - DIED) on father's RANK interacted with AGE_IN_SUI quintiles; lineage (FOUNDER_ID) fixed effects control for persistent clan-level health environments; cohort fixed effects from BIRTHYEAR decade)
# Generated:  2026-03-11 (UTC)
#
# NOTE: Adjust the data path(s) in the 'Data Loading' section before running.
# All regression specifications replicate those executed by the HLER pipeline.
# Robust standard errors follow the same choice as the Python analysis
# (HC3 for OLS; HC1 for FE; cluster-robust for DiD / event-study).
# =============================================================================


# ======================================================================
# ---------------------------------------------------------------------------
# Package Loading
# ---------------------------------------------------------------------------
# Install missing packages:  install.packages(readLines('packages.txt'))

library(fixest)
library(ggplot2)
library(jsonlite)
library(lmtest)
library(modelsummary)
library(sandwich)
library(tidyverse)

# ======================================================================
# ---------------------------------------------------------------------------
# Load Canonical Model Specification
# ---------------------------------------------------------------------------
# model_spec.json is the single source of truth generated by the HLER pipeline.
# It captures the exact variables, fixed effects, and SE choices used in Python.
spec <- fromJSON("model_spec.json")

# ======================================================================
# ---------------------------------------------------------------------------
# Data Loading
# ---------------------------------------------------------------------------
# Data path is read from model_spec.json at runtime:
data <- read_csv(spec$data_source)

# ======================================================================
# ---------------------------------------------------------------------------
# Variable Construction
# ---------------------------------------------------------------------------
# Dep var was a Yes/No character column in Python — convert to 0/1 for LPM:
data <- data %>%
  mutate(DIED = as.integer(DIED == "Yes"))


# ======================================================================
# ---------------------------------------------------------------------------
# Main Regression
# ---------------------------------------------------------------------------
# Build fixed-effects formula from model_spec.json:
indep_vars <- c(spec$independent_variables, spec$controls)
rhs        <- paste(indep_vars, collapse = " + ")
# feols uses ^ to form a compound entity FE (e.g. hhid^line);
# paste with ^ when multiple FE columns, otherwise use single name:
fe_cols <- spec$fixed_effects
fe_part <- if (length(fe_cols) > 1) paste(fe_cols, collapse = "^") else fe_cols[1]
formula_fe <- as.formula(paste(spec$dependent_variable, "~", rhs, "|", fe_part))

# Fixed-effects estimator with robust SEs (type from spec):
model_fe <- feols(formula_fe, data = data, vcov = spec$se_type)
summary(model_fe)

# ======================================================================
# ---------------------------------------------------------------------------
# Heterogeneity Analysis
# ---------------------------------------------------------------------------
# --- by birth order (early vs. late) ---
data <- data %>%
  mutate(BIRTH_ORDER_q = ntile(BIRTH_ORDER, 2))
for (g in 1:2) {
  sub  <- data %>% filter(BIRTH_ORDER_q == g)
  m    <- lm(DIED ~ RANK + AGE_IN_SUI + BIRTH_ORDER + GENERATION + BANNER + BIRTHYEAR + BIRTH_ORDER_SEX, data = sub)
  cat("\n--- by birth order (early vs. late), group", g, "---\n")
  print(coeftest(m, vcov = vcovHC(m, "HC3")))
}

# --- by generation within lineage ---
data <- data %>%
  mutate(GENERATION_q = ntile(GENERATION, 4))
for (g in 1:4) {
  sub  <- data %>% filter(GENERATION_q == g)
  m    <- lm(DIED ~ RANK + AGE_IN_SUI + BIRTH_ORDER + GENERATION + BANNER + BIRTHYEAR + BIRTH_ORDER_SEX, data = sub)
  cat("\n--- by generation within lineage, group", g, "---\n")
  print(coeftest(m, vcov = vcovHC(m, "HC3")))
}

# --- by banner affiliation ---
# Cross-sectional OLS on BANNER == 0 subgroup:
model_het_0 <- lm(DIED ~ RANK + AGE_IN_SUI + BIRTH_ORDER + GENERATION + BANNER + BIRTHYEAR + BIRTH_ORDER_SEX,
                     data = data %>% filter(BANNER == 0))
print(coeftest(model_het_0, vcov = vcovHC(model_het_0, "HC3")))

# Cross-sectional OLS on BANNER == 1 subgroup:
model_het_1 <- lm(DIED ~ RANK + AGE_IN_SUI + BIRTH_ORDER + GENERATION + BANNER + BIRTHYEAR + BIRTH_ORDER_SEX,
                     data = data %>% filter(BANNER == 1))
print(coeftest(model_het_1, vcov = vcovHC(model_het_1, "HC3")))


# ======================================================================
# ---------------------------------------------------------------------------
# Temporal Robustness Check
# ---------------------------------------------------------------------------
# Split at year 1800 (pre / post)
data_pre  <- data %>% filter(YEAR <  1800)
data_post <- data %>% filter(YEAR >= 1800)

model_pre  <- lm(DIED ~ RANK + AGE_IN_SUI + BIRTH_ORDER + GENERATION + BANNER + BIRTHYEAR + BIRTH_ORDER_SEX, data = data_pre)
model_post <- lm(DIED ~ RANK + AGE_IN_SUI + BIRTH_ORDER + GENERATION + BANNER + BIRTHYEAR + BIRTH_ORDER_SEX, data = data_post)

cat("\n--- Pre-1800 ---\n")
print(coeftest(model_pre,  vcov = vcovHC(model_pre,  "HC3")))
cat("\n--- Post-1800 ---\n")
print(coeftest(model_post, vcov = vcovHC(model_post, "HC3")))

# ======================================================================
# ---------------------------------------------------------------------------
# Table Export
# ---------------------------------------------------------------------------
dir.create("tables", showWarnings = FALSE)

modelsummary(list("(1)" = model_fe),
            output = "tables/hler_wp_021_results.tex",
            title  = "Main Regression Results")

modelsummary(list("(1)" = model_fe),
            output = "tables/hler_wp_021_results.csv")

# ======================================================================
# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------
dir.create("figures", showWarnings = FALSE)

# Histogram of outcome variable
p_hist <- ggplot(data, aes(x = DIED)) +
  geom_histogram(bins = 30, fill = "steelblue", colour = "white") +
  labs(title = "Distribution of DIED", x = "DIED", y = "Count") +
  theme_minimal()
ggsave("figures/figure_01_hist_DIED.png", p_hist, width = 7, height = 5)

# Scatter: main predictor vs outcome
p_scatter <- ggplot(data, aes(x = RANK, y = DIED)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", colour = "firebrick") +
  labs(title = "RANK vs DIED", x = "RANK", y = "DIED") +
  theme_minimal()
ggsave("figures/figure_02_scatter_RANK_DIED.png", p_scatter, width = 7, height = 5)

# ======================================================================
# ---------------------------------------------------------------------------
# Replication Consistency Check
# ---------------------------------------------------------------------------
# Compares Python (statsmodels) point estimates against R (model_fe).
# Tolerance: abs(diff) < 1e-6.  Logs a warning for any mismatch found.
if (file.exists("python_coefficients.json")) {
  py_coefs <- fromJSON("python_coefficients.json")
  r_coefs  <- coef(model_fe)
  cat("\n=== Replication Consistency Check ===\n")
  all_ok <- TRUE
  for (nm in names(py_coefs)) {
    if (!is.null(r_coefs[nm]) && !is.na(r_coefs[[nm]])) {
      diff <- abs(r_coefs[[nm]] - py_coefs[[nm]])
      if (diff > 1e-6) {
        warning(sprintf(
          "Replication mismatch: %s | Python=%.8f | R=%.8f | diff=%.2e",
          nm, py_coefs[[nm]], r_coefs[[nm]], diff
        ))
        all_ok <- FALSE
      }
    }
  }
  if (all_ok) cat("All coefficients match within tolerance (1e-6).\n")
} else {
  message("python_coefficients.json not found — skipping consistency check.")
}