# =============================================================================
# Replication Script
# =============================================================================
#
# Paper:      Insurance Scheme Consolidation and Outpatient Care Equity Between Urban and Rural Elderly: Evidence from CHARLS
# Run ID:     hler_wp_030
# Model:      FE_within (Difference-in-differences with wave 3 (2015) as the policy cutoff; treatment group = urban resident insurance holders (ea001s3); control = rural NRCMS enrollees (ea001s4); include individual and community FE; log-transform cost variables)
# Generated:  2026-03-27 (UTC)
#
# NOTE: Adjust the data path(s) in the 'Data Loading' section before running.
# All regression specifications replicate those executed by the HLER pipeline.
# Robust standard errors follow the same choice as the Python analysis
# (HC3 for OLS; HC1 for FE; cluster-robust for DiD / event-study).
# =============================================================================


# ======================================================================
# ---------------------------------------------------------------------------
# Package Loading
# ---------------------------------------------------------------------------
# Install missing packages:  install.packages(readLines('packages.txt'))

library(fixest)
library(ggplot2)
library(jsonlite)
library(lmtest)
library(modelsummary)
library(sandwich)
library(tidyverse)

# ======================================================================
# ---------------------------------------------------------------------------
# Load Canonical Model Specification
# ---------------------------------------------------------------------------
# model_spec.json is the single source of truth generated by the HLER pipeline.
# It captures the exact variables, fixed effects, and SE choices used in Python.
spec <- fromJSON("model_spec.json")

# ======================================================================
# ---------------------------------------------------------------------------
# Data Loading
# ---------------------------------------------------------------------------
# Data path is read from model_spec.json at runtime:
data <- read_csv(spec$data_source)

# ======================================================================
# ---------------------------------------------------------------------------
# Variable Construction
# ---------------------------------------------------------------------------
# Apply sample restrictions matching the Python analysis:
data <- data %>%
  filter(ea001s3 %in% c("是", "否"),
          ea001s4 %in% c("是", "否"))

# Dep var was a Yes/No character column in Python — convert to 0/1 for LPM:
data <- data %>%
  mutate(doctor = as.integer(doctor == "Yes"))

# DiD: construct post indicator and interaction term
# Adjust column names to match your data:
data <- data %>%
  mutate(
    post    = as.integer(wave >= 2015),
    treated = as.integer(ea001s3 == 1),
    did     = post * treated
  )


# ======================================================================
# ---------------------------------------------------------------------------
# Main Regression
# ---------------------------------------------------------------------------
# Build fixed-effects formula from model_spec.json:
indep_vars <- c(spec$independent_variables, spec$controls)
rhs        <- paste(indep_vars, collapse = " + ")
# feols uses ^ to form a compound entity FE (e.g. hhid^line);
# paste with ^ when multiple FE columns, otherwise use single name:
fe_cols <- spec$fixed_effects
fe_part <- if (length(fe_cols) > 1) paste(fe_cols, collapse = "^") else fe_cols[1]
formula_fe <- as.formula(paste(spec$dependent_variable, "~", rhs, "|", fe_part))

# Fixed-effects estimator with robust SEs (type from spec):
model_fe <- feols(formula_fe, data = data, vcov = spec$se_type)
summary(model_fe)

# ======================================================================
# ---------------------------------------------------------------------------
# Heterogeneity Analysis
# ---------------------------------------------------------------------------
# --- by chronic disease burden (median split) ---
data <- data %>%
  mutate(chronic_index_q = ntile(chronic_index, 2))
for (g in 1:2) {
  sub  <- data %>% filter(chronic_index_q == g)
  m    <- lm(doctor ~ ea001s3 + wave + rural2 + chronic_index + doctor_time + totdoc1m + oopdoc1m, data = sub)
  cat("\n--- by chronic disease burden (median split), group", g, "---\n")
  print(coeftest(m, vcov = vcovHC(m, "HC3")))
}

# --- by rural/urban residence ---
# Cross-sectional OLS on rural2 == 0 subgroup:
model_het_0 <- lm(doctor ~ ea001s3 + wave + chronic_index + doctor_time + totdoc1m + oopdoc1m,
                     data = data %>% filter(rural2 == 0))
print(coeftest(model_het_0, vcov = vcovHC(model_het_0, "HC3")))

# Cross-sectional OLS on rural2 == 1 subgroup:
model_het_1 <- lm(doctor ~ ea001s3 + wave + chronic_index + doctor_time + totdoc1m + oopdoc1m,
                     data = data %>% filter(rural2 == 1))
print(coeftest(model_het_1, vcov = vcovHC(model_het_1, "HC3")))


# ======================================================================
# ---------------------------------------------------------------------------
# Table Export
# ---------------------------------------------------------------------------
dir.create("tables", showWarnings = FALSE)

modelsummary(list("(1)" = model_fe),
            output = "tables/hler_wp_030_results.tex",
            title  = "Main Regression Results")

modelsummary(list("(1)" = model_fe),
            output = "tables/hler_wp_030_results.csv")

# ======================================================================
# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------
dir.create("figures", showWarnings = FALSE)

# Histogram of outcome variable
p_hist <- ggplot(data, aes(x = doctor)) +
  geom_histogram(bins = 30, fill = "steelblue", colour = "white") +
  labs(title = "Distribution of doctor", x = "doctor", y = "Count") +
  theme_minimal()
ggsave("figures/figure_01_hist_doctor.png", p_hist, width = 7, height = 5)

# Scatter: main predictor vs outcome
p_scatter <- ggplot(data, aes(x = ea001s3, y = doctor)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", colour = "firebrick") +
  labs(title = "ea001s3 vs doctor", x = "ea001s3", y = "doctor") +
  theme_minimal()
ggsave("figures/figure_02_scatter_ea001s3_doctor.png", p_scatter, width = 7, height = 5)

# ======================================================================
# ---------------------------------------------------------------------------
# Replication Consistency Check
# ---------------------------------------------------------------------------
# Compares Python point estimates against R (model_fe).
# Tolerance: abs(diff) < 1e-6.  Logs a warning for any mismatch found.
if (file.exists("python_coefficients.json")) {
  py_coefs <- fromJSON("python_coefficients.json")
  r_coefs  <- coef(model_fe)
  cat("\n=== Replication Consistency Check ===\n")
  all_ok <- TRUE
  for (nm in names(py_coefs)) {
    if (!is.null(r_coefs[nm]) && !is.na(r_coefs[[nm]])) {
      diff <- abs(r_coefs[[nm]] - py_coefs[[nm]])
      if (diff > 1e-6) {
        warning(sprintf(
          "Replication mismatch: %s | Python=%.8f | R=%.8f | diff=%.2e",
          nm, py_coefs[[nm]], r_coefs[[nm]], diff
        ))
        all_ok <- FALSE
      }
    }
  }
  if (all_ok) cat("All coefficients match within tolerance (1e-6).\n")
} else {
  message("python_coefficients.json not found — skipping consistency check.")
}