# =============================================================================
# Replication Script
# =============================================================================
#
# Paper:      Agricultural Tax Relief and Occupational Reallocation in Rural China: Evidence from the China Health and Nutrition Survey
# Run ID:     hler_wp_020
# Model:      event_study (event study (treatment: t2=2 rural residents, cutoff: 2006); individual FE + relative-time dummies, outcome = probability of farm vs. non-farm occupation (b4))
# Generated:  2026-03-08 (UTC)
#
# NOTE: Adjust the data path(s) in the 'Data Loading' section before running.
# All regression specifications replicate those executed by the HLER pipeline.
# Robust standard errors follow the same choice as the Python analysis
# (HC3 for OLS; HC1 for FE; cluster-robust for DiD / event-study).
# =============================================================================


# ======================================================================
# ---------------------------------------------------------------------------
# Package Loading
# ---------------------------------------------------------------------------
# Install missing packages:  install.packages(readLines('packages.txt'))

library(fixest)
library(ggplot2)
library(jsonlite)
library(lmtest)
library(modelsummary)
library(sandwich)
library(tidyverse)

# ======================================================================
# ---------------------------------------------------------------------------
# Load Canonical Model Specification
# ---------------------------------------------------------------------------
# model_spec.json is the single source of truth generated by the HLER pipeline.
# It captures the exact variables, fixed effects, and SE choices used in Python.
spec <- fromJSON("model_spec.json")

# ======================================================================
# ---------------------------------------------------------------------------
# Data Loading
# ---------------------------------------------------------------------------
# Data path is read from model_spec.json at runtime:
data <- read_csv(spec$data_source)

# ======================================================================
# ---------------------------------------------------------------------------
# Variable Construction
# ---------------------------------------------------------------------------
# Event study: construct relative event-time for treated units
data <- data %>%
  mutate(
    treated   = as.integer(t2 == 1),
    event_time = ifelse(treated == 1, time_col - 2006, NA_real_)
  )


# ======================================================================
# ---------------------------------------------------------------------------
# Main Regression
# ---------------------------------------------------------------------------
# Build event-study formula from model_spec.json:
indep_vars <- c(spec$independent_variables, spec$controls)
indep_vars <- indep_vars[indep_vars != "t2"]
ctrl_part  <- if (length(indep_vars) > 0) paste("+", paste(indep_vars, collapse = " + ")) else ""
fe_part    <- paste(spec$fixed_effects, collapse = " + ")
formula_es <- as.formula(paste(spec$dependent_variable, "~ i(event_time, treated, ref = -1)", ctrl_part, "|", fe_part, "+ wave"))

model_es <- feols(formula_es, data = data,
                  vcov = as.formula(paste("~", spec$cluster)))
iplot(model_es, main = "Event Study: Dynamic Treatment Effects")
summary(model_es)

# ======================================================================
# ---------------------------------------------------------------------------
# Heterogeneity Analysis
# ---------------------------------------------------------------------------
# --- by individual income (t1 proxy) ---
data <- data %>%
  mutate(t1_q = ntile(t1, 2))
for (g in 1:2) {
  sub  <- data %>% filter(t1_q == g)
  m    <- lm(b4 ~ t2 + wave + indinc_cpi, data = sub)
  cat("\n--- by individual income (t1 proxy), group", g, "---\n")
  print(coeftest(m, vcov = vcovHC(m, "HC3")))
}


# ======================================================================
# ---------------------------------------------------------------------------
# Temporal Robustness Check
# ---------------------------------------------------------------------------
# Split at year 2000 (pre / post)
data_pre  <- data %>% filter(wave <  2000)
data_post <- data %>% filter(wave >= 2000)

model_pre  <- lm(b4 ~ t2 + wave + indinc_cpi, data = data_pre)
model_post <- lm(b4 ~ t2 + wave + indinc_cpi, data = data_post)

cat("\n--- Pre-2000 ---\n")
print(coeftest(model_pre,  vcov = vcovHC(model_pre,  "HC3")))
cat("\n--- Post-2000 ---\n")
print(coeftest(model_post, vcov = vcovHC(model_post, "HC3")))

# ======================================================================
# ---------------------------------------------------------------------------
# Table Export
# ---------------------------------------------------------------------------
dir.create("tables", showWarnings = FALSE)

modelsummary(list("(1)" = model_es),
            output = "tables/hler_wp_020_results.tex",
            title  = "Main Regression Results")

modelsummary(list("(1)" = model_es),
            output = "tables/hler_wp_020_results.csv")

# ======================================================================
# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------
dir.create("figures", showWarnings = FALSE)

# Histogram of outcome variable
p_hist <- ggplot(data, aes(x = b4)) +
  geom_histogram(bins = 30, fill = "steelblue", colour = "white") +
  labs(title = "Distribution of b4", x = "b4", y = "Count") +
  theme_minimal()
ggsave("figures/figure_01_hist_b4.png", p_hist, width = 7, height = 5)

# Scatter: main predictor vs outcome
p_scatter <- ggplot(data, aes(x = t2, y = b4)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", colour = "firebrick") +
  labs(title = "t2 vs b4", x = "t2", y = "b4") +
  theme_minimal()
ggsave("figures/figure_02_scatter_t2_b4.png", p_scatter, width = 7, height = 5)

# Event-study coefficient plot (fixest iplot):
png("figures/figure_event_study.png", width = 900, height = 600)
iplot(model_es, main = "Event Study: Dynamic Treatment Effects")
dev.off()

# ======================================================================
# ---------------------------------------------------------------------------
# Replication Consistency Check
# ---------------------------------------------------------------------------
# Compares Python (statsmodels) point estimates against R (model_es).
# Tolerance: abs(diff) < 1e-6.  Logs a warning for any mismatch found.
if (file.exists("python_coefficients.json")) {
  py_coefs <- fromJSON("python_coefficients.json")
  r_coefs  <- coef(model_es)
  cat("\n=== Replication Consistency Check ===\n")
  all_ok <- TRUE
  for (nm in names(py_coefs)) {
    if (!is.null(r_coefs[nm]) && !is.na(r_coefs[[nm]])) {
      diff <- abs(r_coefs[[nm]] - py_coefs[[nm]])
      if (diff > 1e-6) {
        warning(sprintf(
          "Replication mismatch: %s | Python=%.8f | R=%.8f | diff=%.2e",
          nm, py_coefs[[nm]], r_coefs[[nm]], diff
        ))
        all_ok <- FALSE
      }
    }
  }
  if (all_ok) cat("All coefficients match within tolerance (1e-6).\n")
} else {
  message("python_coefficients.json not found — skipping consistency check.")

}
