# =============================================================================
# Replication Script
# =============================================================================
#
# Paper:      Formal Employment-Based Insurance and Outpatient Care Utilisation among Urban Older Adults: Evidence from CHARLS
# Run ID:     hler_wp_029
# Model:      DDML (DDML with individual FE; ea001s1 as binary treatment, nuisance variables include age, edu, retire, pension, chronic_index, log_income, gender fitted via random forest in first stage; separate models for OOP cost and visit count outcomes)
# Generated:  2026-03-22 (UTC)
#
# NOTE: Adjust the data path(s) in the 'Data Loading' section before running.
# All regression specifications replicate those executed by the HLER pipeline.
# Robust standard errors follow the same choice as the Python analysis
# (HC3 for OLS; HC1 for FE; cluster-robust for DiD / event-study).
# =============================================================================


# ======================================================================
# ---------------------------------------------------------------------------
# Package Loading
# ---------------------------------------------------------------------------
# Install missing packages:  install.packages(readLines('packages.txt'))

library(ddml)
library(fixest)
library(ggplot2)
library(jsonlite)
library(lmtest)
library(modelsummary)
library(sandwich)
library(tidyverse)

# ======================================================================
# ---------------------------------------------------------------------------
# Load Canonical Model Specification
# ---------------------------------------------------------------------------
# model_spec.json is the single source of truth generated by the HLER pipeline.
# It captures the exact variables, fixed effects, and SE choices used in Python.
spec <- fromJSON("model_spec.json")

# ======================================================================
# ---------------------------------------------------------------------------
# Data Loading
# ---------------------------------------------------------------------------
# Data path is read from model_spec.json at runtime:
data <- read_csv(spec$data_source)

# ======================================================================
# ---------------------------------------------------------------------------
# Variable Construction
# ---------------------------------------------------------------------------
# Apply sample restrictions matching the Python analysis:
data <- data %>%
  filter(rural2 != "农村",
          age >= 60)


# ======================================================================
# ---------------------------------------------------------------------------
# Main Regression
# ---------------------------------------------------------------------------
# DDML estimation using R ddml package
# Treatment variable and nuisance controls from model_spec.json:
treatment_var <- spec$treatment_var
nuisance_vars <- c(spec$independent_variables, spec$controls)
nuisance_vars <- nuisance_vars[nuisance_vars != treatment_var]

# Keep only columns present in data
nuisance_vars <- nuisance_vars[nuisance_vars %in% names(data)]
analysis_cols <- c(spec$dependent_variable, treatment_var, nuisance_vars)
reg_data <- data[, analysis_cols, drop = FALSE]

# Encode categorical (character/factor) columns as numeric dummies
# For binary columns (e.g. "是"/"否"), convert to 0/1; for multi-level, use dummies
cat_cols <- names(reg_data)[sapply(reg_data, function(x) is.character(x) || is.factor(x))]
for (col in cat_cols) {
  vals <- unique(na.omit(reg_data[[col]]))
  if (length(vals) == 2) {
    reg_data[[col]] <- as.integer(reg_data[[col]] == vals[2])
  } else if (length(vals) > 2 && length(vals) <= 15) {
    # Create dummy columns manually (avoids model.matrix NA row-drop issue)
    for (v in vals[-1]) {
      dummy_name <- paste0(col, "_", v)
      reg_data[[dummy_name]] <- as.integer(reg_data[[col]] == v)
      reg_data[[dummy_name]][is.na(reg_data[[col]])] <- NA
      if (col %in% nuisance_vars) nuisance_vars <- c(nuisance_vars, dummy_name)
    }
    nuisance_vars <- nuisance_vars[nuisance_vars != col]
    reg_data[[col]] <- NULL
  } else {
    reg_data[[col]] <- as.numeric(reg_data[[col]])
  }
}

reg_data <- na.omit(reg_data)
# Ensure all columns are numeric
reg_data <- as.data.frame(lapply(reg_data, as.numeric))

Y <- reg_data[[spec$dependent_variable]]
D <- reg_data[[treatment_var]]
X <- as.matrix(reg_data[, nuisance_vars, drop = FALSE])

ddml_model_type <- spec$ddml_model  # PLR or IRM
ddml_learner    <- spec$ddml_learner # lasso, random_forest, gradient_boosting
ddml_n_folds    <- spec$ddml_n_folds

# Select learner — ddml uses mdl_* wrapper functions from the ddml package
if (ddml_learner == "random_forest") {
  learners <- list(list(fun = mdl_ranger, args = list(num.trees = 100, max.depth = 5)))
} else if (ddml_learner == "gradient_boosting") {
  learners <- list(list(fun = mdl_xgboost, args = list(nrounds = 100, max_depth = 3, verbose = 0)))
} else {
  # Default: lasso via glmnet
  learners <- list(list(fun = mdl_glmnet))
}

# Fit DDML model
if (ddml_model_type == "IRM") {
  model_ddml <- ddml_ate(Y, D, X,
                        learners = learners,
                        sample_folds = ddml_n_folds,
                        silent = TRUE)
} else {
  model_ddml <- ddml_plr(Y, D, X,
                        learners = learners,
                        sample_folds = ddml_n_folds,
                        silent = TRUE)
}
summary(model_ddml)

# ======================================================================
# ---------------------------------------------------------------------------
# Heterogeneity Analysis
# ---------------------------------------------------------------------------
# --- by gender ---
# Cross-sectional OLS on gender == "女性" subgroup:
model_het_女性 <- lm(oopdoc1m ~ ea001s1 + age + edu + retire + pension + chronic_index + wave + rural2,
                     data = data %>% filter(gender == "女性"))
print(coeftest(model_het_女性, vcov = vcovHC(model_het_女性, "HC3")))

# Cross-sectional OLS on gender == "男性" subgroup:
model_het_男性 <- lm(oopdoc1m ~ ea001s1 + age + edu + retire + pension + chronic_index + wave + rural2,
                     data = data %>% filter(gender == "男性"))
print(coeftest(model_het_男性, vcov = vcovHC(model_het_男性, "HC3")))

# --- by chronic disease burden (median split) ---
data <- data %>%
  mutate(chronic_index_q = ntile(chronic_index, 2))
for (g in 1:2) {
  sub  <- data %>% filter(chronic_index_q == g)
  m    <- lm(oopdoc1m ~ ea001s1 + age + edu + retire + pension + chronic_index + gender + wave + rural2, data = sub)
  cat("\n--- by chronic disease burden (median split), group", g, "---\n")
  print(coeftest(m, vcov = vcovHC(m, "HC3")))
}

# --- by retirement status ---
# Cross-sectional OLS on retire == "否" subgroup:
model_het_否 <- lm(oopdoc1m ~ ea001s1 + age + edu + pension + chronic_index + gender + wave + rural2,
                     data = data %>% filter(retire == "否"))
print(coeftest(model_het_否, vcov = vcovHC(model_het_否, "HC3")))

# Cross-sectional OLS on retire == "是" subgroup:
model_het_是 <- lm(oopdoc1m ~ ea001s1 + age + edu + pension + chronic_index + gender + wave + rural2,
                     data = data %>% filter(retire == "是"))
print(coeftest(model_het_是, vcov = vcovHC(model_het_是, "HC3")))


# ======================================================================
# ---------------------------------------------------------------------------
# Table Export
# ---------------------------------------------------------------------------
dir.create("tables", showWarnings = FALSE)

# DDML results — extract coefficients to a data frame for export
ddml_coefs <- data.frame(
  variable = names(coef(model_ddml)),
  theta    = coef(model_ddml),
  se       = sqrt(diag(vcov(model_ddml))),
  row.names = NULL
)
write.csv(ddml_coefs, "tables/hler_wp_029_results.csv", row.names = FALSE)

# ======================================================================
# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------
dir.create("figures", showWarnings = FALSE)

# Histogram of outcome variable
p_hist <- ggplot(data, aes(x = oopdoc1m)) +
  geom_histogram(bins = 30, fill = "steelblue", colour = "white") +
  labs(title = "Distribution of oopdoc1m", x = "oopdoc1m", y = "Count") +
  theme_minimal()
ggsave("figures/figure_01_hist_oopdoc1m.png", p_hist, width = 7, height = 5)

# Scatter: main predictor vs outcome
p_scatter <- ggplot(data, aes(x = ea001s1, y = oopdoc1m)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", colour = "firebrick") +
  labs(title = "ea001s1 vs oopdoc1m", x = "ea001s1", y = "oopdoc1m") +
  theme_minimal()
ggsave("figures/figure_02_scatter_ea001s1_oopdoc1m.png", p_scatter, width = 7, height = 5)

# ======================================================================
# ---------------------------------------------------------------------------
# Replication Consistency Check
# ---------------------------------------------------------------------------
# Compares Python point estimates against R (model_ddml).
# Tolerance: abs(diff) < 1e-3.  Logs a warning for any mismatch found.
if (file.exists("python_coefficients.json")) {
  py_coefs <- fromJSON("python_coefficients.json")
  r_coefs  <- coef(model_ddml)
  cat("\n=== Replication Consistency Check ===\n")
  all_ok <- TRUE
  for (nm in names(py_coefs)) {
    if (!is.null(r_coefs[nm]) && !is.na(r_coefs[[nm]])) {
      diff <- abs(r_coefs[[nm]] - py_coefs[[nm]])
      if (diff > 1e-3) {
        warning(sprintf(
          "Replication mismatch: %s | Python=%.8f | R=%.8f | diff=%.2e",
          nm, py_coefs[[nm]], r_coefs[[nm]], diff
        ))
        all_ok <- FALSE
      }
    }
  }
  if (all_ok) cat("All coefficients match within tolerance (1e-3).\n")
} else {
  message("python_coefficients.json not found — skipping consistency check.")
}